services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: movie_api_db
      MYSQL_ROOT_PASSWORD: "adm@789"
    ports:
      - "3307:3306" # Computer 3307 -> Docker DB 3306
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  app: # This is your NestJS service
    build: .
    ports:
      - "3001:3001" # Computer 3001 -> Docker NestJS 3001
    environment:
      DATABASE_URL: "mysql://root:adm%40789@127.0.0.1:3307/movie_api_db"
    depends_on:
      - db
      
volumes:
  db_data:




#DATABASE_URL cu: "mysql://root:adm%40789@db:3306/movie_api_db"







#services:
#  db:
#    image: mysql:8.0
#    restart: always
#    environment:
#      MYSQL_DATABASE: movie_api_db
#      MYSQL_ROOT_PASSWORD: "adm@789"
#    ports:
#      - "3307:3306"
#    volumes:
#      - db_data:/var/lib/mysql

#volumes:
#  db_data: